# Generated by Django 5.1 on 2024-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tube", "0002_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="thumbnail_image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="video_file",
        ),
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="tube/files/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="post",
            name="thumb_image",
            field=models.ImageField(blank=True, upload_to="tube/images/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
